// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkZb5G1Tf7I6m_XGrtD5BGOzTO40O0oW0',
    appId: '1:677834832533:web:ae29fd2fe6874cb6b8399c',
    messagingSenderId: '677834832533',
    projectId: 'flutter-task-d1831',
    authDomain: 'flutter-task-d1831.firebaseapp.com',
    storageBucket: 'flutter-task-d1831.appspot.com',
    measurementId: 'G-5YCPYT7RNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhjFGk4ekRlvvTCFDdKH6p9_-FhthyVXk',
    appId: '1:677834832533:android:54fea607cbac646db8399c',
    messagingSenderId: '677834832533',
    projectId: 'flutter-task-d1831',
    storageBucket: 'flutter-task-d1831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGQsbIIuwIO-ZPOOS-0BPG8WZ7bG02F9g',
    appId: '1:677834832533:ios:68e7bb5a57526fc1b8399c',
    messagingSenderId: '677834832533',
    projectId: 'flutter-task-d1831',
    storageBucket: 'flutter-task-d1831.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGQsbIIuwIO-ZPOOS-0BPG8WZ7bG02F9g',
    appId: '1:677834832533:ios:68e7bb5a57526fc1b8399c',
    messagingSenderId: '677834832533',
    projectId: 'flutter-task-d1831',
    storageBucket: 'flutter-task-d1831.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkZb5G1Tf7I6m_XGrtD5BGOzTO40O0oW0',
    appId: '1:677834832533:web:e0421e9026885248b8399c',
    messagingSenderId: '677834832533',
    projectId: 'flutter-task-d1831',
    authDomain: 'flutter-task-d1831.firebaseapp.com',
    storageBucket: 'flutter-task-d1831.appspot.com',
    measurementId: 'G-CD08DKHW1X',
  );

}